# Generated by Django 2.2 on 2020-06-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('query', models.CharField(max_length=255)),
                ('tweet_volume', models.PositiveIntegerField()),
            ],
        ),
    ]
