# Generated by Django 2.2 on 2020-07-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='tweet_volume',
            new_name='per_of_spammer',
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='query',
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='url',
        ),
        migrations.AddField(
            model_name='hashtag',
            name='location',
            field=models.TextField(default='Pakistan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hashtag',
            name='related_hashtags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='tweets_colected',
            field=models.PositiveIntegerField(default=1000),
            preserve_default=False,
        ),
    ]
