# Generated by Django 2.2 on 2020-07-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag', '0002_auto_20200706_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='location',
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='related_hashtags',
        ),
        migrations.AddField(
            model_name='hashtag',
            name='spammer_found',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='hashtag',
            field=models.CharField(default='test', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='per_of_spammer',
            field=models.CharField(default='0.0%', max_length=20),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='tweets_colected',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
