# Generated by Django 2.2 on 2020-07-08 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag', '0003_auto_20200708_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spammer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_id', models.PositiveIntegerField(default=0)),
                ('user_id', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(default='none', max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('hashtag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hashtag.Hashtag')),
            ],
        ),
    ]
