# Generated by Django 2.2 on 2020-07-08 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag', '0004_spammer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spammer',
            new_name='SpamTweets',
        ),
    ]
