# Generated by Django 2.2 on 2020-07-08 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag', '0006_spamtweets_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spamtweets',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hashtag.Hashtag'),
        ),
    ]
