# Generated by Django 2.2 on 2020-07-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag', '0007_auto_20200708_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spamtweets',
            name='msg_id',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='spamtweets',
            name='name',
            field=models.CharField(blank=True, default='none', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='spamtweets',
            name='user_id',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
