# Generated by Django 2.2 on 2020-07-08 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag', '0008_auto_20200708_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spamtweets',
            name='id',
        ),
        migrations.AlterField(
            model_name='spamtweets',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hashtag.Hashtag'),
        ),
    ]
